openapi: 3.0.0
info:
  title: Subscriber API
  description: "List, Add, Update and Delete Subscribers"
  termsOfService: http://swagger.io/terms/
  contact:
    name: CompTia
    url: https://www.comptia.com/
    email: dng-root@unnst.com
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT.html
  version: 1.0.0
servers:
- url: http://localhost:3000
  description: Development server
paths:
  /api/items:
    get:
      summary: Retrieve a list of subscribers
      operationId: apiItemsGET
      responses:
        "200":
          description: A list of subscribers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Default
  /api/item/:
    post:
      summary: Create a new subscriber
      operationId: apiItemPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api_item_body'
        required: true
      responses:
        "201":
          description: Subscriber created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Default
  /api/items/{id}:
    patch:
      summary: Update an existing subscriber
      operationId: apiItemsIdPATCH
      parameters:
      - name: id
        in: path
        description: The subscriber ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/items_id_body'
        required: true
      responses:
        "200":
          description: Subscriber updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Default
  /api/item/{id}:
    delete:
      summary: Delete a subscriber
      operationId: apiItemIdDELETE
      parameters:
      - name: id
        in: path
        description: The subscriber ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Subscriber deleted successfully
      x-swagger-router-controller: Default
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        subscribedToChannel:
          type: string
      example:
        name: name
        subscribedToChannel: subscribedToChannel
        id: 0
    api_item_body:
      type: object
      properties:
        name:
          type: string
          example: John Doe
        subscribedToChannel:
          type: string
          example: BitCoin
    items_id_body:
      type: object
      properties:
        name:
          type: string
          example: Jane Doe
        subscribedToChannel:
          type: string
          example: ShebaCoin